### ISSUE TITLE
jamen's abandoned projects

### ISSUE THREAD

**Issue by jamen** [scrapjs/contributing#4]
Hi.  I have a quite a few abandoned projects.  But I'm not sure all would fit the criteria:

 - Ambitious projects from when I was a noob, and probably don't make sense or have clear goals
 - Some packages that are pointless to me, and I don't want to maintain, a lot likely unfinished too
 - Packages names on npm I've renamed and have created leftovers

I also created a tool, [npm-inactive](https://github.com/jamen/npm-inactive), for the purpose of removing abandoned names off my npm profile (into a holding account).  It would be cool if there was some sort of [scrap](https://www.npmjs.com/~scrap) npm account it could default to for this organization. :smile:

Here is lists of the packages in question:

 - [jamen-inactive on npm](https://npmjs.com/~jamen-inactive)
 - [my archived repos on github](https://github.com/search?l=&p=2&q=archived+user%3Ajamen&ref=advsearch&type=Repositories&utf8=%E2%9C%93)

**Comment by dy** [comment]
@jamen hey, yes, this org is exactly for such purpose. If you feel comfortable - transfer all archived repos here. _npm-inactive_ is a really nice tool, should consider using it here :smile:

I hope I will find out time to create some infrastructure for this org, for now just collecting scrap and ideas.

**Comment by reqshark** [comment]
good job guys

add me so I can dump my noob abandonware like:

* [dlr](https://github.com/reqshark/dlr), an electron-based soundcloud downloader w/ awkward setup, plus a couple months after i made that, scd relaunched [a working v2](https://black-burn.ch/app/SCD2)

* [zttp](https://github.com/reqshark/zttp) terrible http backend, nearly impossible to use given you need to install zeromq library on the system. just barely enough of the protocol spec to sometimes send and receive http requests/responses.
